<!DOCTYPE html>
<html lang="pt-br">
 <head>
 <meta charset="utf-8"/>
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <meta name="author" content="Aviators - byaviators.com">
 <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
 <link rel="shortcut icon" href="/assets/img/favicon.png" type="image/png">
 <link rel="stylesheet" href="/assets/css/bootstrap.css" type="text/css">
 <link rel="stylesheet" href="/assets/css/bootstrap-responsive.css" type="text/css">
 <link rel="stylesheet" href="/assets/libraries/chosen/chosen.css" type="text/css">
 <link rel="stylesheet" href="/assets/libraries/bootstrap-fileupload/bootstrap-fileupload.css" type="text/css">
 <link rel="stylesheet" href="/assets/libraries/jquery-ui-1.10.2.custom/css/ui-lightness/jquery-ui-1.10.2.custom.min.css" type="text/css">
 <link rel="stylesheet" href="/assets/css/realia-red_1.css" type="text/css" id="color-variant-default">
 <link rel="stylesheet" href="#" type="text/css" id="color-variant" >
 <title>Imóveis e Serviços</title>
 <script>
function buscarbairro(){
var cidade = ($('#cidade').val());
if(cidade){
var url = 'ajax_buscar_cidades.php?cidade='+cidade;  
$.get(url, function(dataReturn) {

var str=(dataReturn);
var res = replaceAll(str,'[','');
res = replaceAll(res,']','');
res = replaceAll(res,'{','');
res = replaceAll(res,'}','');
var matrizbairros = res.split(',');
var lenmatrizbairros=matrizbairros.length;
var bairro='';
var bairrolimpo = new Array();
var y=0;
for(x=0;x<lenmatrizbairros;x++){
	if(x%2){
		bairro=matrizbairros[x];
		bairrolimpo[y] = replaceAll(bairro,'"','');
	//	alert('bairrolimpo: '+bairrolimpo[y]);
	y++;
	}
}
var lenbairrolimpo = bairrolimpo.length;
var b=0;
var nomebairro = new Array();
var estebairro2;
var matriznomebairro = new Array();
for(z=0;z<lenbairrolimpo;z++){
	estebairro2 = bairrolimpo[z];
	matriznomebairro = estebairro2.split(':');
	nomebairro[b] = matriznomebairro[1];	
	b++;	
  
}
var novaselect='<select name="bairro" id="bairro">';
for (c=0;c<nomebairro.length;c++){
novaselect+='<option value="'+nomebairro[c]+'">'+nomebairro[c]+'</option>';	
}
novaselect+='</select>';
document.getElementById('selectbairro').innerHTML=novaselect;
function replaceAll(string, token, newtoken) {
	while (string.indexOf(token) != -1) {
 		string = string.replace(token, newtoken);
	}
	return string;
}
});
}
    }

 </script>
 </head>
 <body>
<div id="wrapper-outer" >
<div id="wrapper">
<div id="wrapper-inner">
<!-- BREADCRUMB -->
<div class="breadcrumb-wrapper">
   <div class="container">
    <div class="row">
       <div class="span12">
        <div class="account pull-right">
           <ul class="nav nav-pills">
            <li><a href="admin/">Entrar</a></li>
          </ul>
         </div>
      </div>
       <!-- /.span12 --> 
     </div>
    <!-- /.row --> 
  </div>
   <!-- /.container --> 
 </div>
<!-- /.breadcrumb-wrapper --> 

<!-- HEADER -->
<div id="header-wrapper">
   <div id="header">
    <div id="header-inner">
       <div class="container">
        <div class="navbar">
           <div class="navbar-inner">
            <div class="row">
               <div class="logo-wrapper span4"> <a href="#nav" class="hidden-desktop" id="btn-nav">Menu de navegação</a>
                <div class="logo"> <a href="#" title="Home"> <img src="images/logo.png" alt="Home"> </a> </div>
                <!-- /.logo -->
                
                <div class="site-name"> <a href="#" title="Home" class="brand"></a> </div>
                <!-- /.site-name --> 
                
              </div>
               <!-- /.logo-wrapper -->
               
               <div class="info">
                <div class="site-email"> <a href="mailto:contato@imoveiseservicos.com.br">contato@imoveiseservicos.com.br</a> </div>
                <!-- /.site-email -->
                
                <div class="site-phone"> <span>(41) 3282-9955 / 3556-3004</span> </div>
                <!-- /.site-phone --> 
              </div>
               <!-- /.info --> 
               
             </div>
            <!-- /.row --> 
          </div>
           <!-- /.navbar-inner --> 
         </div>
        <!-- /.navbar --> 
      </div>
       <!-- /.container --> 
     </div>
    <!-- /#header-inner --> 
  </div>
   <!-- /#header --> 
 </div>
<!-- /#header-wrapper --> 

<!-- NAVIGATION -->
<div id="navigation">
   <div class="container">
    <div class="navigation-wrapper">
       <div class="navigation clearfix-normal">
        <ul class="nav">
           <li><a href="/">Home</a></li>
           <li><a href="fornecedores">Fornecedores</a></li>
           <li><a href="compradores">Compradores</a></li>
           <li class="menuparent"> <span class="menuparent nolink">Fornecedores</span>
            <ul>
               <li class="menuparent"> <span class="menuparent nolink">Categoria1</span>
                <ul>
                   <li><a href="#">Serviço 1</a></li>
                   <li><a href="#">Serviço 2</a></li>
                   <li><a href="#">Serviço 3</a></li>
                 </ul>
              </li>
               <li class="menuparent"> <span class="menuparent nolink">Categoria2</span>
                <ul>
                   <li><a href="#">Serviço 4</a></li>
                   <li><a href="#">Serviço 5</a></li>
                   <li><a href="#">Serviço 6</a></li>
                 </ul>
              </li>
               <li class="menuparent"> <span class="menuparent nolink">Categoria3</span>
                <ul>
                   <li><a href="#">Serviço 7</a></li>
                   <li><a href="#">Serviço 8</a></li>
                   <li><a href="#">Serviço 9</a></li>
                 </ul>
              </li>
             </ul>
          </li>
           <li><a href="sobre">Como Funciona</a></li>
           <li><a href="anuncios">Anúncios</a></li>
           <li><a href="contato">Contato</a></li>
         </ul>
        <!-- /.nav -->
        
        <form method="get" class="site-search" action="index.php">
           <div class="input-append">
            <input title="Coloque o que deseja procurar." class="search-query span2 form-text" placeholder="Procurar" type="text" name="">
            <button type="submit" class="btn"><i class="icon-search"></i></button>
          </div>
           <!-- /.input-append -->
         </form>
        <!-- /.site-search --> 
      </div>
       <!-- /.navigation --> 
     </div>
    <!-- /.navigation-wrapper --> 
  </div>
   <!-- /.container --> 
 </div>
<!-- /.navigation --> 

<!-- CONTENT -->
<?php echo $this->layout()->content; ?>
<!-- CONTENT -->
<!-- /.bottom-wrapper -->
</div>
<!-- /#content -->
</div>
<!-- /#wrapper-inner -->

<div id="footer-wrapper">
   <div id="footer-top">
    <div id="footer-top-inner" class="container">
       <div class="row">
        <div class="widget span3" style="width: 30%">
           <div class="title">
            <h2>Informa&ccedil;&otilde;es</h2>
          </div>
           <!-- /.title -->
           
           <div class="content">
            <table class="contact">
               <tbody>
                <tr>
                   <th class="address">Endere&ccedil;o:</th>
                   <td>Rua Izabel a Redentora, n&deg; 1050 - S&atilde;o Jos&eacute; dos Pinhais, Centro<br>
                    Paran&aacute;<br></td>
                 </tr>
                <tr>
                   <th class="phone">Telefone:</th>
                   <td>(41) 3282-9955 <br>
                    (41) 3556-3004</td>
                 </tr>
                <tr>
                   <th class="email">E-mail:</th>
                   <td><a href="mailto:contato@imoveiseservicos.com.br">contato@imoveiseservicos.com.br</a></td>
                 </tr>
              </tbody>
             </table>
          </div>
           <!-- /.content --> 
         </div>
        <!-- /.widget -->
        
        <div class="widget span3" >
           <div class="title">
            <h2 class="block-title">Menu</h2>
          </div>
           <!-- /.title -->
           
           <div class="content">
            <ul class="menu nav">
               <li class="first leaf"><a href="#">Principal</a></li>
               <li class="leaf"><a href="#">Im&oacute;veis</a></li>
               <li class="leaf"><a href="#">Servi&ccedil;os</a></li>
               <li class="leaf"><a href="#">Imobili&aacute;rias</a></li>
               <li class="leaf"><a href="#">An&uacute;ncie</a></li>
               <li class="leaf"><a href="#">Contato</a></li>
             </ul>
          </div>
           <!-- /.content --> 
         </div>
        <!-- /.widget -->
        <div class="widget properties span3" style="width: 35%;">
           <div class="title">
            <h2>Localiza&ccedil;&atilde;o</h2>
          </div>
           <!-- /.title -->
           
           <div class="content">
            <iframe width="425" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.br/maps?q=rua+izabel+a+redentora+1050+centro+s%C3%A3o+jos%C3%A9+dos+pinhais&amp;ie=UTF8&amp;hq=&amp;hnear=Rua+Dona+Izabel+A+Redentora,+1050+-+Silveira+da+Motta,+Paran%C3%A1&amp;t=m&amp;ll=-25.523931,-49.204245&amp;spn=0.027109,0.036478&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
            <br />
          </div>
           <!-- /.content --> 
         </div>
        <!-- /.properties-small --> 
        
      </div>
       <!-- /.row --> 
     </div>
    <!-- /#footer-top-inner --> 
  </div>
   <!-- /#footer-top -->
   
   <div id="footer" class="footer container">
    <div id="footer-inner">
       <div class="row">
        <div class="span6 copyright">
           <p>Desenvolvido por <a href="http://www.opisystem.com.br">OPI SYSTEM</a> © 2013 | Todos os direitos reservados.</p>
         </div>
        <!-- /.copyright -->
        
        <div class="span6 share">
           <div class="content">
            <ul class="menu nav">
               <!--
                            <li class="first leaf"><a href="http://www.facebook.com/" class="facebook">Facebook</a></li>
                            <li class="leaf"><a href="http://flickr.net/" class="flickr">Flickr</a></li>
                            <li class="leaf"><a href="http://plus.google.com/" class="google">Google+</a></li>
                            <li class="leaf"><a href="http://www.linkedin.com/" class="linkedin">LinkedIn</a></li>
                            -->
             </ul>
          </div>
           <!-- /.content --> 
         </div>
        <!-- /.span6 --> 
      </div>
       <!-- /.row --> 
     </div>
    <!-- /#footer-inner --> 
  </div>
   <!-- /#footer --> 
 </div>
<!-- /#footer-wrapper -->
</div>
<!-- /#wrapper -->
</div>
<!-- /#wrapper-outer --> 

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3&amp;sensor=true"></script> 
<script type="text/javascript" src="assets/js/jquery.js"></script> 
<script type="text/javascript" src="assets/js/jquery.ezmark.js"></script> 
<script type="text/javascript" src="assets/js/jquery.currency.js"></script> 
<script type="text/javascript" src="assets/js/jquery.cookie.js"></script> 
<script type="text/javascript" src="assets/js/retina.js"></script> 
<script type="text/javascript" src="assets/js/bootstrap.min.js"></script> 
<script type="text/javascript" src="assets/js/carousel.js"></script> 
<script type="text/javascript" src="assets/js/gmap3.min.js"></script> 
<script type="text/javascript" src="assets/js/gmap3.infobox.min.js"></script> 
<script type="text/javascript" src="assets/libraries/jquery-ui-1.10.2.custom/js/jquery-ui-1.10.2.custom.min.js"></script> 
<script type="text/javascript" src="assets/libraries/chosen/chosen.jquery.min.js"></script> 
<script type="text/javascript" src="assets/libraries/iosslider/_src/jquery.iosslider.min.js"></script> 
<script type="text/javascript" src="assets/libraries/bootstrap-fileupload/bootstrap-fileupload.js"></script> 
<script type="text/javascript" src="assets/js/realia.js"></script> 
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','../www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40414414-1', 'byaviators.com');
  ga('send', 'pageview');

</script>
</body>
</html>
