<br /><br />
<div id="view-content">
	<p>View script for controller <b>Administracao</b> and script/action name <b>index</b></p>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"revisao","action"=>"index"),null,true);?>" >Cadastros pendentes</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"tipo","action"=>"index"),null,true);?>" >Cadastros de Tipos</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"categoria","action"=>"index"),null,true);?>" >Cadastros de Categorias</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"segmento","action"=>"index"),null,true);?>" >Cadastros de Segmentos</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"anuncio","action"=>"index"),null,true);?>" >Anúncios</a></li>
</div>