<br /><br />
<div id="view-content">
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"revisao","action"=>"index"),null,true);?>" >Cadastros pendentes</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"tipo","action"=>"index"),null,true);?>" >Cadastros de Tipos</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"categoria","action"=>"index"),null,true);?>" >Cadastros de Categorias</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"segmento","action"=>"index"),null,true);?>" >Cadastros de Segmentos</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"anuncio","action"=>"index"),null,true);?>" >Anúncios</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"noticias","action"=>"index"),null,true);?>" >Noticias</a></li>
        <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"eventos","action"=>"index"),null,true);?>" >Eventos</a></li>
</div>