<div class="row">
  <div class="col-md-5 col-sm-5 col-md-offset-1 col-sm-offset-1">
      <form class="form-inline" role="form" action="">
          
          <?php  if($this->tipo ==0){?>
            <select class="form-control" id='tipo' onchange='window.location="/admin/preferencias/cadastrarcompra/tipo/" + this.value;'>
                <option value=""> Selecione um Tipo</option>
                <?php foreach($this->dadosTipos as $chave => $tipo){
                    echo '<option value='.$tipo['key'].'>'.$tipo['value'].'</option>';
                }?>
            </select>
          <?php }?>
          
          <?php  if($this->tipo !=0 && $this->categoria ==''){?>
            <select class="form-control" id='categoria' onchange='window.location="<?php echo $this->tipo?>/cat/" + this.value;'>
              <option value=""> Selecione uma categoria</option>
              <?php foreach($this->dadosCategorias as $chave => $tipo){
                  echo '<option value='.$tipo['id'].'>'.$tipo['descricao'].'</option>';
              }?>
            </select>
          <?php }?>              
      </form>
      
      <?php 
      $this->form->setAction( $this->url( array("module"=>"admin","controller"=>"preferencias","action"=>"inserir", "tipoPref"=>"compra"),null,true ));
      echo $this->form?>
  </div>
</div>