<script language="JavaScript">
function abrir(URL) {
  var width = 400;
  var height = 400;
  var left = 99;
  var top = 99;
  window.open(URL,'janela', 'width='+width+', height='+height+', top='+top+', left='+left+', scrollbars=yes, status=no, toolbar=no, location=no, directories=no, menubar=no, resizable=no, fullscreen=no');
}
</script>

<h3>Selecione e cadastre os itens pertinentes ao seu ramo de atuação e necessidade de suprimentos</h3>

<div class="row">
    <div class="col-md-5 col-sm-5 col-md-offset-1 col-sm-offset-1">
        <h3>Fornece</h3>
        <a href="javascript:abrir('<?php echo $this->url(array("module"=>"admin","controller"=>"preferencias","action"=>"cadastrarpreferencia","pref"=>"venda"),null,true)?>')" title="Cadastrar preferência de venda"><span class="icon icon-plus"></span></a>
        <hr>
        <?php
            foreach($this->dadosVendas as $tipo=>$dadosCategorias){
                echo"<ul>";
                echo"<li>".$tipo."</li>";
                if(is_array($dadosCategorias)){
                    foreach($dadosCategorias as $categoria => $dadosSegmentos){
                        echo"<ul>";
                        echo"<li>".$categoria."</li>";
                        if(is_array($dadosSegmentos)){
                            echo"<ul>";
                            foreach($dadosSegmentos as $segmento){
                                echo"<li>".$segmento."</li>";
                            }
                            echo"</ul>";
                        }else{
                            echo"<ul>";
                            echo"<li>".$dadosSegmentos."</li>";
                            echo"</ul>";
                        }
                        echo"</ul>";
                    }
                }
                echo"</ul>";
            }
        ?>
    </div>
    
    <div class="col-md-5 col-sm-5 col-md-offset-1 col-sm-offset-1">
        <h3>Compra</h3><a href="javascript:abrir('<?php echo $this->url(array("module"=>"admin","controller"=>"preferencias","action"=>"cadastrarpreferencia","pref"=>"compra"),null,true)?>')" title="Cadastrar preferência de compra"><span class="icon icon-plus"></span></a>
        <hr>
        
        <?php
            foreach($this->dadosCompras as $tipo=>$dadosCategorias){
                echo"<ul>";
                echo"<li>".$tipo."</li>";
                if(is_array($dadosCategorias)){
                    foreach($dadosCategorias as $categoria => $dadosSegmentos){
                        echo"<ul>";
                        echo"<li>".$categoria."</li>";
                        if(is_array($dadosSegmentos)){
                            echo"<ul>";
                            foreach($dadosSegmentos as $segmento){
                                echo"<li>".$segmento."</li>";
                            }
                            echo"</ul>";
                        }else{
                            echo"<ul>";
                            echo"<li>".$dadosSegmentos."</li>";
                            echo"</ul>";
                        }
                        echo"</ul>";
                    }
                }
                echo"</ul>";
            }
        ?>
    </div>
</div>
