<h3>Selecione e cadastre os itens pertinentes ao seu ramo de atuação e necessidade de suprimentos</h3>

<div class="row">
    <div class="col-md-5 col-sm-5 col-md-offset-1 col-sm-offset-1">
        <h3>Fornece</h3>
        <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"","id"=>"{$this->dados['id']}"),null,true)?>" title="Cadastrar preferência de venda"><span class="glyphicon glyphicon-plus"></span></a>
        <hr>
        Exibir em formato de árvore
        <?php foreach($this->dadosVendas as $key=>$value):
            var_dump($value);
        endforeach;
        ?>
        
    </div>
    
    <div class="col-md-5 col-sm-5 col-md-offset-1 col-sm-offset-1">
        <h3>Compra</h3><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"","id"=>"{$this->dados['id']}"),null,true)?>" title="Cadastrar preferência de compra"><span class="glyphicon glyphicon-plus"></span></a>
        <hr>
        
        <?php foreach($this->dadosCompras as $key=>$value):
            
        endforeach;
        ?>
    </div>
</div>
