<h3>Selecione e cadastre os itens pertinentes ao seu ramo de atuação e necessidade de suprimentos</h3>

<div class="row">
    <div class="col-md-5 col-sm-5 col-md-offset-1 col-sm-offset-1">
        <h3>Fornece</h3>
        <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"preferencias","action"=>"cadastrar","tipo"=>"venda"),null,true)?>" title="Cadastrar preferência de venda"><span class="glyphicon glyphicon-plus"></span></a>
        <hr>
        <?php 
        foreach($this->dadosVendas as $key=>$value):
            echo"<ul>";
            echo"<li>".$value['tipo']."</li>";
            foreach($value['categorias'] as $indice => $categoria){
                echo "<ul>";
                echo "<li>".$indice."</li>";
                    echo "<ul>";
                foreach($categoria as $subcategorias){
                    echo "<li>".$subcategorias."</li>";
                }
                    echo "</ul>";
                echo "</ul>";
            }
            echo "</ul>";
        endforeach;
        ?>
        
    </div>
    
    <div class="col-md-5 col-sm-5 col-md-offset-1 col-sm-offset-1">
        <h3>Compra</h3><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"cadastrar","tipo"=>"venda"),null,true)?>" title="Cadastrar preferência de compra"><span class="glyphicon glyphicon-plus"></span></a>
        <hr>
        
        <?php 
        foreach($this->dadosCompras as $key=>$value):
            echo"<ul>";
            echo"<li>".$value['tipo']."</li>";
            foreach($value['categorias'] as $indice => $categoria){
                echo "<ul>";
                echo "<li>".$indice."</li>";
                    echo "<ul>";
                foreach($categoria as $subcategorias){
                    echo "<li>".$subcategorias."</li>";
                }
                    echo "</ul>";
                echo "</ul>";
            }
            echo "</ul>";
        endforeach;
        ?>
    </div>
</div>
