<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>

<script language="JavaScript">
function abrir(URL) {
  var width = 400;
  var height = 400;
  var left = 99;
  var top = 99;
  window.open(URL,'janela', 'width='+width+', height='+height+', top='+top+', left='+left+', scrollbars=yes, status=no, toolbar=no, location=no, directories=no, menubar=no, resizable=no, fullscreen=no');
}

function addAcesso(id){    
    var url = "/admin/anuncio/acesso/id/"+id;
    var result = null;
    $.ajax({
        url: url,
        type: 'get',
        dataType: 'json',
        async: false,
            success: function(data) {
                result = data;
            }
    });
}

</script>
<?php $destaques = $this->destaques;
$videos = $this->dadosVideos;
?>
<div class="row"  style="display:flex">
    <div class="col-md-3" id="destaque_lateral">        
        <div class="row" >
            <div class="col-md-10 header-destaque">
                Destaques
            </div>
            <?php
            foreach($this->dadosAnuncios as $key=>$dadosAnuncio): 
                if(substr($dadosAnuncio['link_imagem'], 0, 7) == 'http://'){
                    $link = $dadosAnuncio['link_imagem'];
                }else{
                    $link = 'http://'.$dadosAnuncio['link_imagem'];
                }
                ?>
               <!--<td id="tableVideo" height="185" width="195">
                  Anunciantes
                </td>-->
                <div class="col-md-10 destaques">
                    <a href="<?php echo $link ?>" target="_blank" onclick="addAcesso(<?php echo $dadosAnuncio['id']?>)">
                        <img class="img-responsive" src="<?php echo $dadosAnuncio['local'].$dadosAnuncio['nome_imagem']?>" alt="<?php echo $dadosAnuncio['nome_imagem']?>" title="<?php echo $dadosAnuncio['titulo']?>"></img> 
                    </a>
                   <!--<img src="imgs/teste_imagem.jpg" class="img-responsive" alt="Logo">-->
               </div>
            <?php
            endforeach;
            ?>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row" style="background-color:green">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <?php foreach($this->dadosBanners as $indice=>$banner): ?>
                    <li data-target="#carousel-example-generic" data-slide-to="<?php echo $indice?>" class="<?php if($indice==0){echo 'active';}?>"></li>
                <?php endforeach;?>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <?php foreach($this->dadosBanners as $indice=>$banner): ?>
                    <div class="item <?php if($indice==0){echo 'active';}?>">
                        <img src="<?php echo $banner['local'].$banner['nome_imagem']?>" alt="<?php echo $banner['titulo']?>" />
                        <div class="carousel-caption">
                            <?php echo $banner['titulo']?>
                        </div>
                    </div>
                <?php endforeach;?>                
            </div>
            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>
        <hr>

        <div class="row" id="destaques">                            
            <div class="col-md-4 center-block">
                <a href="<?php echo $destaques[0]['link_imagem']?>"><img class="img-responsive" src="<?php echo $destaques[0]['local'].$destaques[0]['nome_imagem']?>"></a>
            </div>
            <div class="col-md-4 center-block">
                <a href="<?php echo $destaques[1]['link_imagem']?>"><img class="img-responsive" src="<?php echo $destaques[1]['local'].$destaques[1]['nome_imagem']?>"></a>
            </div>
            <div class="col-md-4 center-block ">
                <a href="<?php echo $destaques[2]['link_imagem']?>"><img class="img-responsive" src="<?php echo $destaques[2]['local'].$destaques[2]['nome_imagem']?>"></a>
            </div>
        </div>
    </div>

    <div class="col-md-3 " id="videos">
        <div class="row">
            <div class="col-md-10 header-destaque pull-right">
                Vídeos
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 destaques pull-right">
                <img src="imgs/teste_imagem.jpg" class="img-responsive" alt="Logo">
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 destaques pull-right">
                <img src="imgs/teste_imagem.jpg" class="img-responsive" alt="Logo">
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 destaques pull-right">
                <img src="imgs/teste_imagem.jpg" class="img-responsive" alt="Logo">
            </div>
        </div>
        <div class="row">
            <div class="col-md-10 destaques pull-right">
                <img src="imgs/teste_imagem.jpg" class="img-responsive" alt="Logo">
            </div>
        </div>
    </div>
</div>