<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>
<body>
    <div class="container">
        <div class="row">
            <div class="span3">
                <table>
                    <tr>
                        <th>Conexões</th>
                    </tr>
                    <tr>
                        <td>Clientes</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Fornecedores</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>Solicitações</td>
                        <td>3</td>
                    </tr>
                </table>
            </div>
            
            <div class="span1"></div>
            
            <div class="span3">
                <table>
                    <tr>
                        <th>Solicitações dos clientes</th>
                    </tr>
                    <tr>
                        <td>Pedidos de orçamento</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Propostas enviadas</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>Propostas aprovadas</td>
                        <td>3</td>
                    </tr>
                </table>
            </div>
            
            <div class="span1"></div>
            
            <div class="span3">
                <table >
                    <tr>
                        <th>Minhas Solicitações</th>
                    </tr>
                    <tr>
                        <td>Orçamentos solicitados</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>Propostas recebidas</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>Propostas aprovadas</td>
                        <td>3</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div id="footer-noticias">
            <div id="sidebarNoticias">    	
            	<table width="100%" height="195px">
                  <tr>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                  </tr>
                </table>
            </div>
        </div>
</body>