<div class="container">
    <div id="main">
        <div class="row">
            <h1 class="page-header">Contato</h1>
            <div class="span8">
                    <div class="properties-grid" >
                        <div class="row">
                            <form action="contato.php" id="contactform" method="post" name="contactForm" style="width:80%" >
                                Nome:<br>  <input type="text" name="name"  id="name" size="40px" value="" style="width:80%" /><br>
                                E-mail: <br><input type="text" name="email"  id="email" value="" style="width:80%"/><br>
                                Assunto: <br><input type="text" name="subject"  id="subject" value="" style="width:80%"/><br>
                                Mensagem:<br> <textarea name="message" id="message"  cols="2" rows="6" style="width:80%"></textarea><br>
                                <label>&nbsp;</label>
                                <input type="submit" name="submit" class="buttoncontact" id="buttonsend" value="Enviar" style="font-size:20px" />
                           </form>  
                        </div><!-- /.row -->
                    </div><!-- /.properties-grid -->
            </div>
            <div class="sidebar span3">
                    <div class="properties-grid" >
                        <div class="row">
                            DADOS E FORMAS ADICIONAIS DE CONTATO
                        </div><!-- /.row -->
                    </div><!-- /.properties-grid -->
            </div><!-- /.content -->
        </div><!-- /.properties -->
    </div>
    <div class="bottom-wrapper">
   <div class="bottom container">
    <div class="bottom-inner row">
       <div class="item span4">
        <div class="address decoration"></div>
        <h2><a>Anuncie</a></h2>
        <p>Clique para se Cadastrar e Anunciar Grá;tis, depois faça o login. Voc&ecirc; fará; o seu próprio anúncio escolhendo o Estado, a Cidade, depois a Categoria e a Subcategoria onde deseja que ele apareça.</p>
        <a href="#" class="btn btn-primary">Saiba mais</a> 
       </div>
       <!-- /.item -->
       
       <div class="item span4">
        <div class="gps decoration"></div>
        <h2><a>Encontre com facilidade</a></h2>
        <p>O nosso site oferece o serviço perfeito para quem quer comprar ou vender um imá;vel, divulgar serviços entre outros.  Al&eacute;m do site de Imóveis e Serviços &eacute; ser uma ferramenta simples, fá;cil e á;gil para os usuá;rios.</p>
        <a href="#" class="btn btn-primary">Saiba mais</a> </div>
       <!-- /.item -->
       
       <div class="item span4">
        <div class="key decoration"></div>
        <h2><a>Imóvel ou serviço</a></h2>
        <p>Possibilidade de achar o imovel ou o serviço que tanto precisa ou quer no mesmo site tudo em um unico lugar sem complicação sem demora venha conhecer os ...</p>
        <a href="#" class="btn btn-primary">Saiba mais</a> </div>
       <!-- /.item --> 
     </div>
    <!-- /.bottom-inner --> 
  </div>
   <!-- /.bottom --> 
 </div>
</div>