<center><h1 >Contato</h1></center>
<iframe class="map" width="90%" height="350" src="https://maps.google.com.br/maps?q=rua+izabel+a+redentora+1050+centro+s%C3%A3o+jos%C3%A9+dos+pinhais&amp;ie=UTF8&amp;hq=&amp;hnear=Rua+Dona+Izabel+A+Redentora,+1050+-+Silveira+da+Motta,+Paran%C3%A1&amp;t=m&amp;ll=-25.523931,-49.204245&amp;spn=0.027109,0.036478&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
<div class='row'>
    <div class="span9">    
        <div class="span3">
            <h3 class="address">Endereço</h3>
            <p class="content-icon-spacing">
             Rua Izabel a Redentora, n° 1050 <br> São José dos Pinhais - Centro
            </p>
        </div>
        <div class="span2">
            <h3 class="call-us">Contato</h3>
            <p class="content-icon-spacing">
            (41) 3282-9955 <br>
                                            (41) 3283-2780
            </p>
        </div>
        <div class="span3">
            <h3 class="email">Email</h3>
            <p class="content-icon-spacing">
                <a href="mailto:contato@imoveiseservicos.com.br">contato@imoveiseservicos.com.br</a><br>
            </p>
        </div>
    </div>  
</div>
            