<div class="container">
    <div id="main">
        <div class="row">
            <h1 class="page-header">Contato</h1>
            <div class="span8">
                    <div class="properties-grid" >
                        <div class="row">
                            <form action="contato.php" id="contactform" method="post" name="contactForm" style="width:80%" >
                                Nome:<br>  <input type="text" name="name"  id="name" size="40px" value="" style="width:80%" /><br>
                                E-mail: <br><input type="text" name="email"  id="email" value="" style="width:80%"/><br>
                                Assunto: <br><input type="text" name="subject"  id="subject" value="" style="width:80%"/><br>
                                Mensagem:<br> <textarea name="message" id="message"  cols="2" rows="6" style="width:80%"></textarea><br>
                                <label>&nbsp;</label>
                                <input type="submit" name="submit" class="buttoncontact" id="buttonsend" value="Enviar" style="font-size:20px" />
                           </form>  
                        </div><!-- /.row -->
                    </div><!-- /.properties-grid -->
            </div>
            <div class="sidebar span3">
                    <div class="properties-grid" >
                        <div class="row">
                            DADOS E FORMAS ADICIONAIS DE CONTATO
                        </div><!-- /.row -->
                    </div><!-- /.properties-grid -->
            </div><!-- /.content -->
        </div><!-- /.properties -->
    </div>
</div>