<?php
/**
 * @author Gustavo Del Negro <gustavodelnegro@gmail.com>
 * @version v0.1
 * @since v0.1
 */
?>

<head>
    <link href="/dist/css/bootstrap.css" rel="stylesheet">
    <style>
        /*
 * Base structure
 */

/* Move down content because we have a fixed navbar that is 50px tall */
    body {
        padding-top: 50px;
    }

/*
 * Global add-ons
 */

    .sub-header {
        padding-bottom: 10px;
        border-bottom: 1px solid #eee;
    }   

/*
 * Sidebar
 */

    /* Hide for mobile, show later */
    .sidebar {
        display: none;
    }
    
    @media (min-width: 768px) {
    .sidebar {
        position: fixed;
        top: 0;
        left: 0;
        bottom: 0;
        z-index: 1000;
        display: block;
        padding: 70px 20px 20px;
        background-color: #494748;
        border-right: 2px solid #E47136;
    }
    
}

/* Sidebar navigation */
    .nav-sidebar {
        margin-left: -20px;
        margin-right: -21px; /* 20px padding + 1px border */
        margin-bottom: 20px;
    }
    .nav-sidebar > li > a {
        padding-left: 20px;
        padding-right: 20px;
    }
    .nav-sidebar > .active > a {
        color: #E47136;
        background-color: #494748;
        border-right: 1px solid #E47136;
    }


    /*
    * Main content
    */

    .main {
        padding: 20px;
    }
    @media (min-width: 768px) {
    .main {
        padding-left: 40px;
        padding-right: 40px;
        }
    }
    .main .page-header {
        margin-top: 0;
    }
    
    /*
    * Placeholder dashboard ideas
    */

    .placeholders {
        margin-bottom: 30px;
        text-align: center;
    }
    .placeholders h4 {
        margin-bottom: 0;
    }
    .placeholder {
        margin-bottom: 20px;
    }
    .placeholder img {
        border-radius: 50%;
    }
    </style>
        
</head>
<body>

    <div class="navbar navbar-fixed-top"  style="background-color: #494748;border-bottom: 2px solid #E47136" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand">O Supply</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right" >
            <li ><a href="#" style='color:#E47136'>Logout</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#" target="conteudo">Visão Geral</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Painel de controle</h1>
          <?php echo $this->layout()->content; ?>
        </div>
        </div>
      </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/dist/js/bootstrap.min.js"></script>
  </body>