<?php
/**
 * @author Gustavo Del Negro <gustavodelnegro@gmail.com>
 * @version v0.1
 * @since v0.1
 */
?>

<head>
    <title>O'Supply</title>
    <link rel="shortcut icon" href="/images/favicon.ico" type="image/ico">
    <meta charset="utf-8">
    <link href="/dist/css/bootstrap.css" rel="stylesheet">
    <style>
        /*
 * Base structure
 */

/* Move down content because we have a fixed navbar that is 50px tall */
    body {
        padding-top: 50px;
    }

/*
 * Global add-ons
 */

    .sub-header {
        padding-bottom: 10px;
        border-bottom: 1px solid #eee;
    }   

/*
 * Sidebar
 */

    /* Hide for mobile, show later */
    .sidebar {
        display: none;
    }
    
    @media (min-width: 768px) {
    .sidebar {
        position: fixed;
        top: 0;
        left: 0;
        bottom: 0;
        z-index: 1000;
        display: block;
        padding: 70px 20px 20px;
        background-color: #494748;
        border-right: 2px solid #E47136;
    }
    
}

/* Sidebar navigation */
    .nav-sidebar {
        margin-left: -20px;
        margin-right: -21px; /* 20px padding + 1px border */
        margin-bottom: 20px;
    }
    .nav-sidebar > li > a {
        padding-left: 20px;
        padding-right: 20px;
        color: #E47136;
        background-color: #494748;
    }
    .nav-sidebar > .active > a {
        color: #E47136;
        background-color: #494748;
        border-right: 1px solid #E47136;
    }
    
    .nav-sidebar > .active{
        font-weight: bold;
        color: #E47136;
        background-color: #494748;
        border-right: 1px solid #E47136;
        padding-left: 5px;
    }
    
    .nav > .active > a{
        color: #E47136;
        background-color: #494748;
        border-right: 1px solid #E47136;
    }


    /*
    * Main content
    */

    .main {
        padding: 20px;
    }
    @media (min-width: 768px) {
    .main {
        padding-left: 40px;
        padding-right: 40px;
        }
    }
    .main .page-header {
        margin-top: 0;
        padding-top: 20px;
    }
    
    /*
    * Placeholder dashboard ideas
    */

    .placeholders {
        margin-bottom: 30px;
        text-align: center;
    }
    .placeholders h4 {
        margin-bottom: 0;
    }
    .placeholder {
        margin-bottom: 20px;
    }
    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
     }
    .form-signin .form-signin-heading,
    .form-signin .form-control {
        position: relative;
        font-size: 16px;
        height: auto;
        padding: 10px;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }       
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="text"] {
        margin-bottom: -1px;
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }

    .form-signin input[type="submit"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
        max-width: 100%;
    }
    </style>
        
</head>
<body>

    <div class="navbar navbar-fixed-top"  style="background-color: #494748;border-bottom: 2px solid #E47136" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand">O Supply</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right" >
              <li style="border: 1px solid #E47136;border-bottom: 0px;border-radius: 6px">
                  <img src="/images/1.jpg" width="200px" height="64px">
              </li>
              <li><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"index","id"=>$this->layout()->usuario->id),null,true);?>" style='color:#E47136'>Editar Cadastro</a></li>
            <li>
                <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"index","action"=>"logout"),null,true);?>" style="color:#E47136">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
            <div class="col-sm-2 col-xs-2 sidebar">
              <ul class="nav nav-sidebar">
       <?php if($this->layout()->usuario->grupo == 1){?>
                  <li class="active"><h4>Revisão de Cadastros</h4></li>
                    <ul class='nav'>
                        <li class="active"><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"revisao","action"=>"index"),null,true);?>" >Revisar cadastros pendentes</a></li>
                    </ul> 
       <?php }?>
                  <li class="active"><h4>Preferências</h4></li>
                <ul class='nav'>
                    <li class="active"><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"preferencias","action"=>"index"),null,true);?>" >Ver preferências</a></li>
                </ul>
                  <li class="active"><h4>Itens</h4></li>
                <ul class='nav'>
                    <li class="active"><a href="" >Itens a venda</a></li>
                    <li class="active"><a href="#" >Itens para comprar</a></li>
                </ul>
                  <li class="active"><h4>Orçamento</h4></li>
                <ul class='nav'>
                    <li class="active"><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"index"),null,true);?>" >Ver todos os orçamentos</a></li>
                    <li class="active"><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"new"),null,true);?>" >Solicitar Orçamento</a></li>
                    <li class="active"><a href="#" >Enviar Orçamentos</a></li>
                    <li class="active"><a href="#" >Orçamentos Recebidos</a></li>
                    <li class="active"><a href="#" >Orçamentos Aprovados</a></li>
                </ul>
                  <li class="active"><h4>Compras</h4></li>
                <ul class='nav'>
                    <li class="active"><a href="#">Compras Realizadas</a></li>
                </ul>
              </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
              <?php echo $this->layout()->content; ?>
            </div>
        </div>
      </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/dist/js/bootstrap.min.js"></script>
  </body>