<div class="row">
    <div class="col-md-3">
        <img src="/imgs/logotipo-anucie.png" class="img-responsive" alt="Logotipo Anuncie">
    </div>
    <div class="col-md-6">
        Encontre produtos, serviços, componentes, ferramentas, equipamentos, profissionais da área e muito mais.

        Desenvolva novos clientes,parceiros e fornecedores.

        Divulgue seus Produtos e Serviços para seu Público Alvo.

        Sua empresa disponível em todo o território nacional.

        Cadastre sua empresa e conheça as vantagens de usar o "O supply"
    </div>
    <div class="col-md-3">
        Sua empresa possui catálogo digital?
        Então torne-o disponível para consulta no:
        <a href="#"><img src="/imgs/botaoSaibaComo.png" class="img-responsive" alt="Saiba como"></a>
    </div>
</div>
<hr>

<div class="row" class='footer'>
    <div id="footer">
        <table width="900px" height="25px" style="color:#0000000">
              <tr>
                  <td height="25" width="100"><img style="margin-left:-10px; margin-bottom:-8px; margin-top:-80px;" src="/imgs/logotipo-parcial.png"/></td>
                    <td height="25" width="200">SOBRE</td>
                    <td height="25" width="200">MENU</td>
                    <td height="25" width="200">INFORMAÇÕES</td>
                    <td height="25" width="200">ATENDIMENTO</td>
              </tr>
        </table>
    </div>
    <div id="footer" class='footer_meio'>
        <table class="tabela_footer" width="900px" height="25px">
              <tr>
                <td height="25" width="100">&nbsp;</td>
                <td height="25" width="200" style="text-align:left; vertical-align:top">
                    <ul>
                            <li>O Supply</li>
                    </ul>
                </td>
                <td height="25" width="200" style="text-align:left; vertical-align:top">
                    <ul>
                            <li><a href="/index" style="text-decoration:none; color:#FFFFFF;">Home</a></li>
                            <li><a href="/comofunciona" style="text-decoration:none; color:#FFFFFF;">Como Funciona</a></li>
                            <li><a href="/compradores" style="text-decoration:none; color:#FFFFFF;">Compradores</a></li>
                            <li><a href="/fornecedores" style="text-decoration:none; color:#FFFFFF;">Fornecedores</a></li>
                            <li><a href="/anuncie" style="text-decoration:none; color:#FFFFFF;">Anuncie</a></li>
                            <li><a href="/contato" style="text-decoration:none; color:#FFFFFF;">Contato</a></li>
                    </ul></td>
                <td height="25" width="200" style="text-align:left; vertical-align:top">
                    <ul>
                            <li><a href="/perguntasfrequentes" style="text-decoration:none; color:#FFFFFF;">Perguntas Frequentes</a></li>
                            <li><a href="/termosecondicoes" style="text-decoration:none; color:#FFFFFF;">Termos e Condições</a></li>
                            <li><a href="/politicasdeconfidencialidade" style="text-decoration:none; color:#FFFFFF;">Politicas de Confidencialidade</a></li>
                            <li><a href="/planosdeadesao"  style="text-decoration:none; color:#FFFFFF;">Planos de Adesão</a></li>
                    </ul></td>
                <td height="25" width="200" style="text-align:left; vertical-align:top">
                    <ul>
                            <li><a href="/contato" style="text-decoration:none; color:#FFFFFF;">Fale Conosco</a></li>
                    </ul>
                </td>
              </tr>
        </table>
        <center><h5>Desenvolvido por Opi System @ 2014 | Todos os direitos reservados</h5></center>
    </div>
</div>