<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <script src="/js/jquery-2.1.1.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <title>OSupply - Tudo em manutenção industrial em um único portal.</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <style>
            .header-destaque{
                background-color: #E46C0A;
                text-align: center;
                color: #FFF;
                font-weight: bolder;
                border: 3px solid #CCCCCC;
                font-family: "Open Sans",sans-serif;
                font-weight: 700;
                text-transform: uppercase;
                font-size: 14px;
            }
            .destaques{
                border: 3px solid #CCCCCC;
                //border-bottom: 0px;
                border-top: 0px;
            }
            .noticias{
                border:3px solid #CCCCCC;      
            }
            
            .navbar{
                background-color: #E46C0A;
                
            }
            .navbar-rounded{
                height: 35px;
                    min-height: 20px;
                    max-height: 35px;
                margin-top: 10px;
                border-radius: 10px;
                    border-top-left-radius: 10px;
                    border-top-right-radius: 10px;
                    border-bottom-right-radius: 10px;
                    border-bottom-left-radius: 10px;
            }
            
            .navbar-rounded .btn{
                background-color: transparent;
                color: #000;
                border-radius: 5px;
                    border-top-left-radius: 5px;
                    border-top-right-radius: 5px;
                    border-bottom-right-radius: 5px;
                    border-bottom-left-radius: 5px;
            }
            
            .center-block {
                display: block;
                margin-left: auto;
                margin-right: auto;
                
            }
            
            .navbar-default .navbar-nav > li > a {
                color: #FFF;
                font-family: "Open Sans",sans-serif;
                font-weight: 700;
                text-transform: uppercase;
                font-size: 14px;
            }
            
            .navbar-default .navbar-nav > .active > a, .navbar-default .navbar-nav > .active > a:hover, .navbar-default .navbar-nav > .active > a:focus {    
                color: #333;
                background-color: transparent;
            }   
            
            @media only screen 
            and (min-width : 1224px) {
                .row #destaques{
                    margin-top: 15%;
                }
            }                
            
            #footer{
                background-color: #E46C0A;
            }
            
            .footer_meio{                
                margin-top: 2%;
            }
            
            .tabela_footer{
                color:#FFFFFF; 
                text-align:left; 
                vertical-align:top;
            }
            .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
            }
           .form-signin .form-signin-heading,
           .form-signin .checkbox {
               margin-bottom: 10px;
           }
           .form-signin .checkbox {
               font-weight: normal;
           }
           .form-signin .form-control {
               position: relative;
               font-size: 16px;
               height: auto;
               padding: 10px;
               -webkit-box-sizing: border-box;
               -moz-box-sizing: border-box;
               box-sizing: border-box;
           }       
           .form-signin .form-control:focus {
               z-index: 2;
           }
           .form-signin input[type="text"] {
               margin-bottom: -1px;
               border-bottom-left-radius: 0;
               border-bottom-right-radius: 0;
           }
           .form-signin input[type="password"] {
               margin-bottom: 10px;
               border-top-left-radius: 0;
               border-top-right-radius: 0;
           }
            
        </style>
    </head>
    <body>        
        <!-- HEADER -->
        <?php include_once('header.php'); ?>
        <!-- HEADER -->
        
        <div class="container">
                <!-- CONTEUDO-->
                <div class='form-signin'>
                    <h2 class='form-signin-heading'>Por favor, <br> identifique-se</h2>
                    <?php echo $this->loginForm ?>
                </div>
                <!-- CONTEUDO -->
            <hr>
            <!-- FOOTER -->
            <?php include_once('footer.php'); ?>
            <!-- FOOTER -->
        </div>
    </body>
</html>