<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>OSupply - Tudo em manutenção industrial em um único portal.</title>
<link rel="stylesheet" type="text/css" href="/dist/css/screen.css"> 
<link rel="stylesheet" type="text/css" href="/dist/css/theme.css">
<link rel="stylesheet" href="/assets/css/bootstrap.css" type="text/css">
<link rel="stylesheet" href="/assets/css/bootstrap-responsive.css" type="text/css">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <style>

        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
         }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin .checkbox {
            font-weight: normal;
        }
        .form-signin .form-control {
            position: relative;
            font-size: 16px;
            height: auto;
            padding: 10px;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }       
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-left-radius: 0;
            border-bottom-right-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
</head>
<body>
    <div id="outer-container">
        <?php include_once('header.php'); ?>
        <!-- FOOTER -->
        <div style="clear: both">
        </div>        
        <div class='form-signin'>
                <h2 class='form-signin-heading'>Por favor, <br> identifique-se</h2>
                <?php echo $this->loginForm ?>
        </div> 
    	
        <div style="clear: both">
        </div>
        
        <div id="footer" style="margin-top:80px;">
            <table width="900px" height="25px" style="color:#0000000">
                  <tr>
                    <td height="25" width="100"><img style="margin-left:-10px; margin-bottom:-8px; margin-top:-80px;" src="/images/logotipo-parcial.png"/></td>
                    <td height="25" width="200">SOBRE</td>
                    <td height="25" width="200">MENU</td>
                    <td height="25" width="200">INFORMAÇÕES</td>
                    <td height="25" width="200">ATENDIMENTO</td>
                  </tr>
            </table>
        </div>
        
        <div style="clear: both">
        </div>
        
        <div id="footer">
            <table width="900px" height="25px" style="color:#FFFFFF; text-align:left; vertical-align:top">
                  <tr>
                    <td height="25" width="100">&nbsp;</td>
                    <td height="25" width="200" style="text-align:left; vertical-align:top">
                    	<ul>
                        	<li>O Supply</li>
                        </ul>
                    </td>
                    <td height="25" width="200" style="text-align:left; vertical-align:top">
                    	<ul>
                        	<li><a href="/" style="text-decoration:none; color:#FFFFFF;">Home</a></li>
                        	<li><a href="/comofunciona" style="text-decoration:none; color:#FFFFFF;">Como Funciona</a></li>
                        	<li><a href="/compradores" style="text-decoration:none; color:#FFFFFF;">Compradores</a></li>
                        	<li><a href="/fornecedores" style="text-decoration:none; color:#FFFFFF;">Fornecedores</a></li>
                        	<li><a href="/anuncie" style="text-decoration:none; color:#FFFFFF;">Anuncie</a></li>
                        	<li><a href="/contato" style="text-decoration:none; color:#FFFFFF;">Contato</a></li>
                        </ul></td>
                    <td height="25" width="200" style="text-align:left; vertical-align:top">
                    	<ul>
                        	<li><a href="/perguntasfrequentes" style="text-decoration:none; color:#FFFFFF;">Perguntas Frequentes</a></li>
                        	<li><a href="/termosecondicoes" style="text-decoration:none; color:#FFFFFF;">Termos e Condições</a></li>
                        	<li><a href="/politicasdeconfidencialidade" style="text-decoration:none; color:#FFFFFF;">Politicas de Confidencialidade</a></li>
                        	<li><a href="/planosdeadesao"  style="text-decoration:none; color:#FFFFFF;">Planos de Adesão</a></li>
                        </ul></td>
                    <td height="25" width="200" style="text-align:left; vertical-align:top">
                    	<ul>
                        	<li><a href="contato.php" style="text-decoration:none; color:#FFFFFF;">Fale Conosco</a></li>
                        </ul>
                    </td>
                  </tr>
            </table>
        </div>
        
        <div id="footer">
            <h4>Desenvolvido por Opi System @ 2014 | Todos os direitos reservados</h4>
        </div>
        
        <!-- FOOTER -->
    </div>
</body>
</html>

<script>
	$(document).ready(function(){	
			$("#slider").easySlider({
				auto: true, 
				continuous: true,
				numeric: true
			});
		});	
</script>