<div class="bottom-wrapper">
   <div class="bottom container">
    <div class="bottom-inner row">
       <div class="item span4">
        <div class="address decoration"></div>
        <h2><a>Anuncie</a></h2>
        <p>Clique para se Cadastrar e Anunciar Grá;tis, depois faça o login. Voc&ecirc; fará; o seu próprio anúncio escolhendo o Estado, a Cidade, depois a Categoria e a Subcategoria onde deseja que ele apareça.</p>
       </div>
       <!-- /.item -->
       
       <div class="item span4">
        <div class="gps decoration"></div>
        <h2><a>Encontre com facilidade</a></h2>
        <p>O nosso site oferece o serviço perfeito para quem quer comprar ou vender um imá;vel, divulgar serviços entre outros.  Al&eacute;m do site de Imóveis e Serviços &eacute; ser uma ferramenta simples, fá;cil e á;gil para os usuá;rios.</p>
       </div>
       <!-- /.item -->
       
       <div class="item span4">
            <div class="key decoration"></div>
            <h2><a>Imóvel ou serviço</a></h2>
            <p>Possibilidade de achar o imovel ou o serviço que tanto precisa ou quer no mesmo site tudo em um unico lugar sem complicação sem demora venha conhecer os ...</p>
        </div>
       <!-- /.item --> 
     </div>
    <!-- /.bottom-inner --> 
    <center><a href="<?php echo $this->url(array("module"=>"default","controller"=>"cadastro","action"=>"index"),null,true);?>" class="btn btn-primary">Cadastre-se</a></center>
  </div>
   <!-- /.bottom --> 
 </div>