<?php
echo "<div class=\"container-fluid\">";    
    echo "<div class=\"row\">";
        echo"<div class=\"col-md-6 col-md-offset-2\">";
            echo $this->formEndereco;
        echo "</div><!-- DIV COL-MD-6 -->";
    echo "</div> <!-- ROW-->";
echo "</div>";
?>

<a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"index","id"=>$this->id),null,true);?>" title="Voltar"><span class="glyphicon glyphicon-arrow-left"></span></a>