<?php
echo "<div class=\"row\">";
    echo"<div class=\"col-md-4 \">";
        echo $this->formUsuario;
    echo "</div><!-- DIV COL-MD-4 -->";
echo "</div> <!-- ROW-->";
    
echo "<div class=\"row\">";
    echo"<div class=\"col-md-4 \">";
        echo $this->formTipoPessoa;
    echo "</div><!-- DIV COL-MD-4 -->";
echo "</div> <!-- ROW-->";
?>

<a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cadastro"),null,true)?>"" title="Voltar"><span class="glyphicon glyphicon-arrow-left"></span></a>