<h2>Informações de cadastro</h2>
<br>
<h3>Dados Pessoais</h3>
<p>
    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"edit","id"=>"{$this->dados['id']}"),null,true)?>" title="Editar cadastro"><i class="icon icon-pencil"></i></a>
    
    <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"show","id"=>"{$this->dados['id']}"),null,true)?>" title="Editar cadastro"><span class="icon icon-search"></span></a>
</p>

<br>
<address>
    <strong><?php echo $this->dados['nome']?></strong>,
    <a href="mailto:<?php echo $this->dados['emailContato']?>"><?php echo $this->dados['emailContato']?></a><br>
    Tipo de cadastro: <?php if($this->dados['tipoPessoa'] == 1){echo 'Pessoa Física';}else{ echo 'Pessoa Jurídica';}?>
</address>
<hr>
<h3>Endereços Cadastrados</h3>
<a href="<?php echo $this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"adicionarendereco","id"=>"{$this->dados['id']}"),null,true)?>" title="Adicionar Endereço"><span class="icon icon-plus"></span></a>
<hr>
<div class="row">
    <?php
    $i = 0;
    foreach ($this->dados['enderecos'] as $indice => $endereco) {
        if($indice==0 AND $indice % 2 !=0){
            echo "<div class=\"row\">";
        }
        
            echo "<div class=\"col-md-4 \">";
                echo "<address>";
                echo"<strong>".$endereco['tipoEndereco']."</strong><br>";
                if($endereco['apelido'] != ''){
                        echo "<strong> Apelido: </strong>".$endereco['apelido']."<br>";
                    }else{
                        echo "<br>";
                    }
                    echo $endereco['logradouro'].','.$endereco['numero']."<br>";
                    if($endereco['complemento'] != ''){
                        echo $endereco['complemento']."<br>";
                    }else{
                        echo "<br>";
                    }
                    echo $endereco['cidade'].','.$endereco['estado'].' - '.$endereco['CEP']."<br>";
                echo "</address>";
            echo "<hr>";
            echo "</div>";
            echo "<div class=\"col-md-2\">";?>
                <?php
                
                echo "<a href='".$this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"editarendereco","id"=>"{$endereco['idEndereco']}"),null,true)."' title=\"Editar endereço\"><span class=\"icon icon-pencil\"></span></a>";
                echo " ";
                echo "<a href='".$this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"removerendereco","id"=>"{$endereco['idEndereco']}"),null,true)."' onclick=\"javascript:return confirm('Você tem certeza que quer excluir este endereço?')\" title=\"Remover endereço\"><span class=\"icon icon-remove\"></span></a>";
            echo "</div>";
            $i=$i++;
        if($i>0 AND $i % 2 ==0){
            echo "</div>"; 
        }
    }?>
</div>