<h2>Informações de cadastro</h2>
<br>
<address>
    <strong>NOME PESSOA</strong>,
    <a href="mailto:#">first.last@example.com</a>
</address>
<hr>
<address>
  <strong>Endereço Comercial</strong><br>
  795 Folsom Ave, Suite 600<br>
  San Francisco, CA 94107<br>
  <abbr title="Phone">P:</abbr> (123) 456-7890
</address>
<address>
  <strong>Endereço Residencial</strong><br>
  795 Folsom Ave, Suite 600<br>
  San Francisco, CA 94107<br>
  <abbr title="Phone">P:</abbr> (123) 456-7890
</address>