<h2>Informações de cadastro</h2>
<br>
<address>
    <strong><?php echo $this->dados['nome']?></strong>,
    <a href="mailto:<?php echo $this->dados['emailContato']?>"><?php echo $this->dados['emailContato']?></a>
</address>
<hr>

<?php

foreach($this->dados['enderecos'] as $key=>$value){
    foreach($value as $chave=>$valor){
        ?>
        <address>
            <strong>Endereço Comercial</strong><br>
            <?php echo $valor['logradouro'].','.$valor['numero']?><br>
            <?php echo $valor['complemento']?>
            
            <?php echo $valor['cidade'].','.$valor['estado'].' - '.$valor['CEP']?><br>
        </address>
<?php
    }
}