<div class="row">
    <div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2">
        <?php echo $this->formOrcamento ?>
    </div>
</div>
<?php
?>
<div class="row">
    <div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2">
        <h3>Itens desse orçamento</h3>
        <table class="table-bordered table-condensed table-striped table-hover">
            <tr>
                <td>Descricao</td>
                <td>Quantidade</td>
            </tr>
            <?php
            foreach($this->dados as $chave => $produto){?>
            <tr>
                <td><?php echo $produto['descricao'] ?></td>
                <td><?php echo $produto['quantidade'] ?></td>
            </tr>
            <?php }?>
        </table>

        <a href="#" class="btn btn-primary">Adicionar Itens</a>
    </div>
</div>