<h2>Edição de orçamento</h2>
<div class="row">
    <div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-3">
        <?php echo $this->formOrcamento ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
        <center>
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
            <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
                <tr>
                     <th><center>Id</center></th>
                     <th><center>Descrição</center></th>                     
                     <th><center>Quantidade</center></th>
                     <th><center>Ações</center></th>
                </tr>
                <?php foreach($this->paginator AS $key => $item):?>
                <tr>
                    <td><center><?php  echo $item['produto']?></center></td>
                    <td><center><?php  echo $item['descricao']?></center></td>
                    <td><center><?php  echo $item['quantidade']?></center></td>
                    <td><center>
                      <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"delitem","id"=>"{$item['produto']}","orcamento"=>"{$this->id}"),null,true)?>" title="Remover Item do Orçamento"><span class="glyphicon glyphicon-remove"></span></a>
                      </center>
                    </td>
                </tr>
                <?php endforeach;?>
            </table>
            <center><?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?></center>
                
        <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"produtos","action"=>"compra","orcamento"=>"{$this->id}"),null,true)?>" class="btn btn-primary">Adicionar Itens</a>
    </div>
</div>