<div class='container'>
    <h2>Edição de orçamento</h2>
<div class="row">
    <div class="col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-3">
        <?php echo $this->formOrcamento ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
        <center>
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
            <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
                <tr>
                     <th><center>Id</center></th>
                     <th><center>Descrição</center></th>                     
                     <th><center>Quantidade</center></th>
                     <th><center>Especificação</center></th>
                     <th><center>Ações</center></th>
                </tr>
                <?php foreach($this->paginator AS $key => $item):?>
                <tr>
                    <td><center><?php  echo $item['produto']?></center></td>
                    <td><center><?php  echo $item['descricao']?></center></td>
                    <td><center><?php  echo $item['quantidade']?></center></td>
                    <td>
                        <center>
                            <a href="<?php echo $item['especificacao']?>" download="Especificacao_<?php echo $item['especificacao']?>"><span class="icon icon-download"></a></span>
                        </center>
                    </td>
                    <td><center>
                      <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"delitem","id"=>"{$item['produto']}","orcamento"=>"{$this->id}"),null,true)?>" title="Remover Item do Orçamento"><i class="icon icon-remove"></i></a>  
                      <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"upload","id"=>"{$item['produto']}","orcamento"=>"{$this->id}"),null,true)?>" title="Adicionar especificação"><span class="icon icon-upload"></span></a>
                      </center>
                    </td>
                </tr>
                <?php endforeach;?>
            </table>
            <center><?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?></center>
                
        <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"produtos","action"=>"compra","orcamento"=>"{$this->id}"),null,true)?>" class="btn btn-primary">Adicionar Itens</a>
    </div>
</div>
<hr>
    <div id="footer-noticias">
            <div id="sidebarNoticias">    	
            	<table width="100%" height="195px">
                  <tr>
                    <?php
                        foreach($this->dadosAnuncios as $key=>$dadosAnuncio): 

                            if(substr($dadosAnuncio['link_imagem'], 0, 7) == 'http://'){
                                $link = $dadosAnuncio['link_imagem'];
                            }else{
                                $link = 'http://'.$dadosAnuncio['link_imagem'];
                            }
                            ?>
                            <td id="tableVideo" height="185" width="185">
                                <a href="<?php echo $link ?>" target="_blank" onclick="addAcesso(<?php echo $dadosAnuncio['id']?>)">
                                    <img width="185" height="" src="<?php echo $dadosAnuncio['local'].$dadosAnuncio['nome_imagem']?>" alt="<?php echo $dadosAnuncio['nome_imagem']?>" title="<?php echo $dadosAnuncio['titulo']?>"></img> 
                                </a>
                            </td>
                            <td></td>
                        <?php
                        endforeach;
                    ?>
                  </tr>
                </table>
            </div>
        </div>
</div>