<script language="JavaScript">
function abrir(URL) {
  var width = 400;
  var height = 400;
  var left = 99;
  var top = 99;
  window.open(URL,'janela', 'width='+width+', height='+height+', top='+top+', left='+left+', scrollbars=yes, status=no, toolbar=no, location=no, directories=no, menubar=no, resizable=no, fullscreen=no');
}

function addAcesso(id){    
    var url = "/admin/anuncio/acesso/id/"+id;
    var result = null;
    $.ajax({
        url: url,
        type: 'get',
        dataType: 'json',
        async: false,
            success: function(data) {
                result = data;
            }
    });
}

$(function() {
    $( "#data_inicial" ).datepicker({
        showOn: "button",
        buttonImage: "/images/calendario.gif",
        buttonImageOnly: true,
        dateFormat: 'yy-mm-dd',
        showOtherMonths: true,
        selectOtherMonths: true,
            dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
            dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
            dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
            monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
            monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],


    });
});    

$(function() {
    $( "#data_final" ).datepicker({
        showOn: "button",
        buttonImage: "/images/calendario.gif",
        buttonImageOnly: true,
        dateFormat: 'yy-mm-dd',
        showOtherMonths: true,
        selectOtherMonths: true,
            dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],
            dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
            dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
            monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
            monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],


    });
});

</script>
<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>
<body>
    <div class="container">
        <div class="row">
            <div class="span11">
                <center>
                    <form class="form-inline" method="post">
                        <input type="text" class="input-small" placeholder="Data Inicial" name="data_inicial" id="data_inicial">
                        <input type="text" class="input-small" placeholder="Data final" name="data_final" id="data_final">
                        <button type="submit" class="btn">Pesquisar</button>
                    </form>
                    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
                    <p class="text-right"> <a class="btn btn-primary" href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"new"),null,true)?>">Solicitar Orçamento</a></p>
                    <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
                   <tr>
                        <th><center>Id</center></th>
                        <th><center>Status</center></th>
                        <th><center>Descrição</center></th>        
                        <th><center>Data de Criação</center></th>
                        <th><center>Propostas Recebidas</center></th>
                        <th><center>Ações</center></th>
                   </tr>
                   <?php foreach($this->paginator AS $key => $orcamento):?>
                   <tr>
                        <td><center><?php  echo $orcamento['id']?></center></td>
                    <td><center><?php switch ($orcamento['status']) {
                                case 1:
                                    echo "Ativo";
                                    break;
                                case 2:
                                    echo "Fechado";
                                default:
                                    break;
                            } $orcamento['id']
                                
                                ?></center></td>
                        <td><center><?php  echo $orcamento['descricao']?></center></td>
                        <td><center><?php echo $orcamento['dtCriacao']?></center></td>
                        <td><center><?php echo $orcamento['totalPropostas']?></center></td>
                      <td><center>
                         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"show","id"=>"{$orcamento['id']}"),null,true)?>" title="Ver Orçamento"><span class="icon icon-search"></span></a>
                         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"propostas","id"=>"{$orcamento['id']}"),null,true)?>" title="Ver Propostas"><span class="icon icon-envelope"></span></a>
                         <?php if($orcamento['status']!=2){?>
                         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"edit","id"=>"{$orcamento['id']}"),null,true)?>" title="Editar Orçamento"><i class="icon icon-pencil"></i></a>
                         <?php }?>
                         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"deletar","id"=>"{$orcamento['id']}"),null,true)?>" title="Excluir Orçamento"><span class="icon icon-remove"></span></a>
                         <?php if($orcamento['status']!=2){?>
                         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"fechar","id"=>"{$orcamento['id']}"),null,true)?>" title="Fechar Orçamento"><span class="icon icon-lock"></span></a>
                         <?php }?>
                         <?php if($orcamento['status']==2){?>
                         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"fechar","id"=>"{$orcamento['id']}"),null,true)?>" title="Enviar Orçamento"><span class="icon icon-share"></span></a>
                         <?php }?>
                         </center>
                      </td>
                   </tr>
                   <?php endforeach;?>
                </table>
                    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

                </center>
            </div>
        </div>
        
    </div>
    <hr>
    <div id="footer-noticias">
            <div id="sidebarNoticias">    	
            	<table width="100%" height="195px">
                  <tr>
                    <?php
                        foreach($this->dadosAnuncios as $key=>$dadosAnuncio): 

                            if(substr($dadosAnuncio['link_imagem'], 0, 7) == 'http://'){
                                $link = $dadosAnuncio['link_imagem'];
                            }else{
                                $link = 'http://'.$dadosAnuncio['link_imagem'];
                            }
                            ?>
                            <td id="tableVideo" height="185" width="185">
                                <a href="<?php echo $link ?>" target="_blank" onclick="addAcesso(<?php echo $dadosAnuncio['id']?>)">
                                    <img width="185" height="" src="<?php echo $dadosAnuncio['local'].$dadosAnuncio['nome_imagem']?>" alt="<?php echo $dadosAnuncio['nome_imagem']?>" title="<?php echo $dadosAnuncio['titulo']?>"></img> 
                                </a>
                            </td>
                            <td></td>
                        <?php
                        endforeach;
                    ?>
                    <!-- <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td> -->
                  </tr>
                </table>
            </div>
        </div>
</body>