<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>
<body>
<center>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <p class="text-right"> <a class="btn btn-primary" href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"new"),null,true)?>">Solicitar Orçamento</a></p>
    <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
   <tr>
        <th><center>Id</center></th>
        <th><center>Descrição</center></th>        
        <th><center>Data de Criação</center></th>
        <th><center>Propostas Recebidas</center></th>
        <th><center>Ações</center></th>
   </tr>
   <?php foreach($this->paginator AS $key => $orcamento):?>
   <tr>
        <td><center><?php  echo $orcamento['id']?></center></td>
        <td><center><?php  echo $orcamento['descricao']?></center></td>
        <td><center><?php echo $orcamento['dtCriacao']?></center></td>
        <td><center><?php echo $orcamento['totalPropostas']?></center></td>
      <td><center>
          <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"show","id"=>"{$orcamento['id']}"),null,true)?>" title="Ver Orçamento"><span class="glyphicon glyphicon-search"></span></a>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"propostas","id"=>"{$orcamento['id']}"),null,true)?>" title="Ver Propostas"><span class="glyphicon glyphicon-envelope"></span></a>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"edit","id"=>"{$orcamento['id']}"),null,true)?>" title="Editar Orçamento"><i class="icon icon-pencil"></i></a>
         </center>
      </td>
   </tr>
   <?php endforeach;?>
</table>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    
</center>
</body>