<table class="table-bordered table-condensed table-striped table-hover">
    <tr>
        <td>Descricao</td>
        <td>Quantidade</td>
    </tr>
<?php
    foreach($this->dados as $chave => $produto){?>
    <tr>
        <td><?php echo $produto['descricao'] ?></td>
        <td><?php echo $produto['quantidade'] ?></td>
    </tr>
    <?php }?>
</table>

<input type="submit" value="Enviar" class="btn btn-primary">