<head>
</head>
<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>
<body>
    <center>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
        <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
            <tr>
                 <th><center>Id</center></th>
                 <th><center>Valor</center></th>        
                 <th><center>Data de Criação</center></th>
                 <th><center>Ações</center></th>
            </tr>
            <?php foreach($this->paginator AS $key => $proposta):?>
            <tr>
                 <td><center><?php  echo $proposta['id']?></center></td>
                 <td><center><?php  echo $proposta['valor']?></center></td>
                 <td><center><?php echo $proposta['dtCriacao']?></center></td>
               <td><center>
                  <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"propostas","id"=>"{$proposta['id']}"),null,true)?>" title="Aprovar"><span class="glyphicon glyphicon-check"></span></a>
                  </center>
               </td>
            </tr>
           <?php endforeach;?>
        </table>
        <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"index"),null,true);?>" title="Voltar"><span class="glyphicon glyphicon-arrow-left"> Voltar</span></a>
    </center>
</body>