<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>
<body>
    <div class="container">
        <div class="row">
            <div class="span2">
                <table>
                    <tr>
                        <th>Meus Fornecedores</th>
                    </tr>
                    <tr>
                        <?php 
                            if(!empty($this->relacionamentosFornecedores)){
                                foreach($this->relacionamentosFornecedores as $indice => $dados){
                                    if($dados['Solicitado']==$this->nomeUsuario){
                                        echo "<td>".$dados['Solicitante']."</td>";
                                    }else{
                                        echo "<td>".$dados['Solicitado']."</td>";
                                    }
                                    echo "<td><a href='".$this->url(array("module"=>"admin","controller"=>"rede","action"=>"remover","id"=>"{$dados['idRelacionamento']}"),null,true)."' onclick=\"javascript:return confirm('Você tem certeza que quer remover essa pessoa da sua rede?')\" title=\"Remover conexão\"><i class=\"icon-remove\"></i></a></td>";
                                }
                            }else{
                                echo "<td>Você não tem relacionamento com fornecedores, aproveita e faça agora mesmo</td>";
                            }
                        ?>
                    </tr>
                </table>
            </div>
            
            <div class="span1"></div>
            
            <div class="span2">
                <table>
                    <tr>
                        <th>Meus Clientes</th>
                    </tr>
                    <tr>
                        <?php if(!empty($this->relacionamentosClientes)){
                            foreach($this->relacionamentosClientes as $indice => $dados){
                                    if($dados['Solicitado']==$this->nomeUsuario){
                                        echo "<td>".$dados['Solicitante']."</td>";
                                    }else{
                                        echo "<td>".$dados['Solicitado']."</td>";
                                    }
                                    echo "<td><a href='".$this->url(array("module"=>"admin","controller"=>"rede","action"=>"remover","id"=>"{$dados['idRelacionamento']}"),null,true)."' onclick=\"javascript:return confirm('Você tem certeza que quer remover essa pessoa da sua rede?')\" title=\"Remover conexão\"><i class=\"icon-remove\"></i></a></td>";
                                }
                        }else{
                            echo "<td>Você não tem relacionamento com clientes, aproveita e faça agora mesmo</td>";
                        }
                        ?>
                    </tr>
                    
                </table>
            </div>
            
            <div class="span5">
                <table >
                    <tr>
                        <th>Buscar</th>
                    </tr>
                    <tr>
                    <form class="form-search" action="" method="POST">
                            <td>
                                <input type="text" name="nome" id="nome" class="input-medium search-query">
                            </td>
                            <td>
                                <button type="submit" class="btn">Buscar</button>
                            </td>
                                
                            </form>
                        </td>
                    </tr>
                    <?php 
                    if(isset($this->dados)){
                        foreach($this->dados as $dados):
                            echo "<tr>";
                                echo "<form action='".$this->url(array("module"=>"admin","controller"=>"rede","action"=>"adicionar"),null,true)."' method=\"POST\">";
                                    echo "<input type=\"hidden\" name =\"id\" value=\"{$dados['id']}\">";
                                    echo "<td> {$dados['nome']} </td>";                                
                                    echo "<td>";
                                    echo '<select name="tipoRelacionamento">';
                                        foreach($this->tipoRelacionamento as $indice=>$dadosTipo){
                                            echo "<option value=\"{$dadosTipo['key']}\">{$dadosTipo['value']}</option>";
                                        }
                                    echo '</select>';
                                    echo '</td>';
                            //echo "<td><a href='".$this->url(array("module"=>"admin","controller"=>"rede","action"=>"adicionar","id"=>"{$dados['id']}"),null,true)."' onclick=\"javascript:return confirm('Você tem certeza que quer adicionar essa pessoa à sua rede?')\" title=\"Adicionar conexão\"><i class=\"icon-ok\"></i></a></td>";
                                    echo "<td><input type=\"submit\" value=\"Adicionar\"></td>";
                                echo "</form>";
                            echo "</tr>";
                        endforeach;
                    }
                    ?>
                </table>
            </div>
        </div>
    </div>
    <hr>
    <div id="footer-noticias">
            <div id="sidebarNoticias">    	
            	<table width="100%" height="195px">
                  <tr>
                    <?php
                        foreach($this->dadosAnuncios as $key=>$dadosAnuncio): 

                            if(substr($dadosAnuncio['link_imagem'], 0, 7) == 'http://'){
                                $link = $dadosAnuncio['link_imagem'];
                            }else{
                                $link = 'http://'.$dadosAnuncio['link_imagem'];
                            }
                            ?>
                            <td id="tableVideo" height="185" width="185">
                                <a href="<?php echo $link ?>" target="_blank" onclick="addAcesso(<?php echo $dadosAnuncio['id']?>)">
                                    <img width="185" height="" src="<?php echo $dadosAnuncio['local'].$dadosAnuncio['nome_imagem']?>" alt="<?php echo $dadosAnuncio['nome_imagem']?>" title="<?php echo $dadosAnuncio['titulo']?>"></img> 
                                </a>
                            </td>
                            <td></td>
                        <?php
                        endforeach;
                    ?>
                    <!-- <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td>
                    <td id="tableVideo" height="185" width="185">Anunciantes Categorias</td>
                    <td></td> -->
                  </tr>
                </table>
            </div>
        </div>
</body>