<style>
    table{
        width: 100%
    }
</style>
    
<h2>Revisão de cadastros pendentes</h2>
<br>

<div class="row">
    <div class="col-md-5 ">
        <h3>Cadastros de usuários</h3>
        <br>
        <div class="table-responsive">
            <table class="table-bordered table-condensed table-striped table-hover">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Data de cadastro</th>
                    <th>Ações</th>
                </tr>
                <?php foreach($this->dadosUsuario as $chave => $usuario):
                    echo "<tr>";
                        echo "<td>".$usuario['id']."</td>";
                        echo "<td>".$usuario['nome']."</td>";
                        echo "<td>".$usuario['dtCriacao']."</td>";
                        echo "<td>";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"show","id"=>"{$usuario['id']}","ctrl"=>"revisao"),null,true)." title=\"Ver cadastro\"><span class=\"glyphicon glyphicon-search\"></span></a>";
                        echo " ";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"aprovar","id"=>"{$usuario['id']}","tipo"=>"usr"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer aprovar este cadastro?')\" title=\"Aprovar cadastro\"><span class=\"glyphicon glyphicon-check\"></span></a>";
                        echo " ";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"deletar","id"=>"{$usuario['id']}","tipo"=>"usr"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer excluir este cadastro?')\" title=\"Deletar cadastro\"><span class=\"glyphicon glyphicon-remove\"></span></a>";
                        echo " ";
                        echo "</td>";
                    echo "</tr>";
                endforeach;?>
            </table>
        </div>
        <?php echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"show","tipo"=>"usr"),null,true)." title=\"Ver mais\">Ver mais...</a>";?>
    </div>
    <div class="col-md-5 col-md-offset-1">
       <h3>Cadastros de Categorias</h3>
       <br>
        <div class="table-responsive">
            <table class="table-bordered table-condensed table-striped table-hover">
                <tr>
                    <th>Id</th>
                    <th>Descrição</th>
                    <th>Data de Cadastro</th>
                    <th>Ações</th>
                </tr>
                <?php foreach($this->dadosCategorias as $chave => $categoria):
                    echo "<tr>";
                        echo "<td>".$categoria['id']."</td>";
                        echo "<td>".$categoria['descricao']."</td>";
                        echo "<td>".$categoria['dtCriacao']."</td>";
                        echo "<td>";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"categoria","action"=>"show","id"=>"{$categoria['id']}","ctrl"=>"revisao"),null,true)." title=\"Ver cadastro\"><span class=\"glyphicon glyphicon-search\"></span></a>";
                        echo " ";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"aprovar","id"=>"{$categoria['id']}","tipo"=>"cat"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer aprovar este cadastro?')\" title=\"Aprovar cadastro\"><span class=\"glyphicon glyphicon-check\"></span></a>";
                        echo " ";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"deletar","id"=>"{$categoria['id']}","tipo"=>"cat"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer excluir este cadastro?')\" title=\"Deletar cadastro\"><span class=\"glyphicon glyphicon-remove\"></span></a>";
                        echo " ";
                        echo "</td>";
                    echo "</tr>";
                endforeach;?>
            </table>
        </div>
        <?php echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"show","tipo"=>"cat"),null,true)." title=\"Ver mais\">Ver mais...</a>";?>
    </div>
</div>
    
<div class="row">
    <div class="col-md-5 ">
        <h3>Cadastros de Sub-Categorias</h3>
        <br>
            <div class="table-responsive">
                <table class="table-bordered table-condensed table-striped table-hover">
                    <tr>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>Data de cadastro</th>
                        <th>Ações</th>
                    </tr>
                    <?php foreach($this->dadosSubCategorias as $chave => $subCategoria):
                    echo "<tr>";
                        echo "<td>".$subCategoria['id']."</td>";
                        echo "<td>".$subCategoria['descricao']."</td>";
                        echo "<td>".$subCategoria['dtCriacao']."</td>";
                        echo "<td>";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"segmento","action"=>"show","id"=>"{$subCategoria['id']}","ctrl"=>"revisao"),null,true)." title=\"Ver cadastro\"><span class=\"glyphicon glyphicon-search\"></span></a>";
                        echo " ";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"aprovar","id"=>"{$subCategoria['id']}","tipo"=>"subcat"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer aprovar este cadastro?')\" title=\"Aprovar cadastro\"><span class=\"glyphicon glyphicon-check\"></span></a>";
                        echo " ";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"deletar","id"=>"{$subCategoria['id']}","tipo"=>"subcat"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer excluir este cadastro?')\" title=\"Deletar cadastro\"><span class=\"glyphicon glyphicon-remove\"></span></a>";
                        echo " ";
                        echo "</td>";
                    echo "</tr>";
                endforeach;?>
                </table>
            </div>
            <?php echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"show","tipo"=>"subcat"),null,true)." title=\"Ver mais\">Ver mais...</a>";?>
    </div>
    <div class="col-md-5 col-md-offset-1 ">
        <h3>Cadastros de Itens</h3>
        <br>
            <div class="table-responsive">
                <table class="table-bordered table-condensed table-striped table-hover">
                    <tr>
                        <th>Id</th>
                        <th>Descrição</th>
                        <th>Data de Cadastro</th>
                        <th>Ações</th>
                    </tr>
                    <?php foreach($this->dadosItens as $chave => $item):
                    echo "<tr>";
                        echo "<td>".$item['id']."</td>";
                        echo "<td>".$item['descricao']."</td>";
                        echo "<td>".$item['dtCriacao']."</td>";
                        echo "<td>";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"produto","action"=>"show","id"=>"{$item['id']}","ctrl"=>"revisao"),null,true)." title=\"Ver cadastro\"><span class=\"glyphicon glyphicon-search\"></span></a>";
                        echo " ";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"aprovar","id"=>"{$item['id']}","tipo"=>"item"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer aprovar este cadastro?')\" title=\"Aprovar cadastro\"><span class=\"glyphicon glyphicon-check\"></span></a>";
                        echo " ";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"deletar","id"=>"{$item['id']}","tipo"=>"item"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer excluir este cadastro?')\" title=\"Deletar cadastro\"><span class=\"glyphicon glyphicon-remove\"></span></a>";
                        echo " ";
                        echo "</td>";
                    echo "</tr>";
                endforeach;?>
                    <tr>
                </table>
            </div>
            <?php echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"show","tipo"=>"item"),null,true)." title=\"Ver mais\">Ver mais...</a>";?>
    </div>
</div>