<head>
</head>
<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}
?>
<body>
    <h2>Revisão de Cadastros de <?php echo $this->titulo?></h2>
<center>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
        <tr>
             <th><center>Id</center></th>
             <?php
             if(strtoupper($this->tipo)!='USR'){
                echo "<th><center>Descrição</center></th>";
             }else{
                echo "<th><center>Nome</center></th>"; 
             }
             ?>        
             <th><center>Data de Criação</center></th>
             <th><center>Ações</center></th>
        </tr>
        <?php foreach($this->paginator AS $key => $dados):?>
        <tr>
             <td><center><?php  echo $dados['id']?></center></td>
             <td><center><?php  
             if(strtoupper($this->tipo)!='USR'){
                echo $dados['descricao'];
             }else{
                echo $dados['nome']; 
             }
             
             ?></center></td>
             <td><center><?php echo $dados['dtCriacao']?></center></td>
           <td><center><?php
              echo "<a href=".$this->url(array("module"=>"admin","controller"=>"cadastro","action"=>"show","id"=>"{$usuario['id']}","ctrl"=>"revisao"),null,true)." title=\"Ver cadastro\"><span class=\"glyphicon glyphicon-search\"></span></a>";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"aprovar","id"=>"{$usuario['id']}","tipo"=>"{$this->tipo}"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer aprovar este cadastro?')\" title=\"Aprovar cadastro\"><span class=\"glyphicon glyphicon-check\"></span></a>";
                        echo "<a href=".$this->url(array("module"=>"admin","controller"=>"revisao","action"=>"deletar","id"=>"{$usuario['id']}","tipo"=>"{$this->tipo}"),null,true)." onclick=\"javascript:return confirm('Você tem certeza que quer excluir este cadastro?')\" title=\"Deletar cadastro\"><span class=\"glyphicon glyphicon-remove\"></span></a>";
                        ?>
              </center>
           </td>
        </tr>
        <?php endforeach;?>
    </table>    
</center>
<a href="<?php echo $this->url(array("module"=>"admin","controller"=>"revisao","action"=>"index"),null,true);?>" title="Voltar"><span class="glyphicon glyphicon-arrow-left"></span></a>
</body>