<script>
    var matriz=<?php echo json_encode($this->dadosPreferencias); ?>;
    
    function teste(){
        var valor = $('#tipo').find(":selected").text();        
        if(valor != 'Selecione um tipo'){
            $('#teste').val(valor);
            
        }if(valor == 'Selecione um tipo'){
            $('#teste').val('');
        }
    }
</script>
<?php
$tipos = array();
$categorias = array();
    foreach($this->dadosPreferencias as $chave=>$valor){
        $tipos[]=$valor['tipo'];
    }
    
    foreach($this->dadosPreferencias as $key=>$value){
        foreach($tipos as $chave=>$valor){
            if(in_array($valor, $value)){
                echo $valor;
            }
        }
    }
?>
<br>
<br>
<br>
<br>
<select name="tipo" id="tipo" onchange="teste()">
    <option value="0">Selecione um tipo</option>
    <?php    
    foreach($this->dadosPreferencias as $key=>$value){
        echo "<option value='".$value['tipo']."'>".$value['tipo']."</option>";
    }
    ?>
</select>
<input type="text" value="" id="teste">