<head>
</head>
<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>
<body>
<center>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <p class="text-right"> <a class="btn btn-primary" href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"new"),null,true)?>">Solicitar Orçamento</a></p>
    <form method="post" action="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"new"),null,true)?>">
        <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
            <tr>
                 <th><center>Selecionar</center></th>
                 <th><center>Descrição</center></th>        
                 <th><center>Quantidade</center></th>
                 <th><center>Data de Cadastro</center></th>
                 <th><center>Ações</center></th>
            </tr>
            <?php foreach($this->paginator AS $key => $produto):?>
            <tr>
                <td><center><input type="checkbox" name="produtos[]" value="<?php echo $produto['id']?>"></center></td>
                 <td><center><?php  echo $produto['produto']?></center></td>
                 <td><center><input type="text" name="quantidade[]" value="<?php echo $produto['quantidade']?>"></center></td>
                 <td><center><?php echo $produto['dtCriacao']?></center></td>
                 <td><center>
                         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"propostas","id"=>"{$produto['id']}"),null,true)?>" title="Ver Propostas"><span class="glyphicon glyphicon-envelope"></span></a>
                     </center>
                 </td>
            </tr>
            <?php endforeach;?>
        </table>    
        <input type="submit" value="Solicitar orçamento dos itens selecionados" class="btn btn-primary">
    </form>
</center>
</body>