<head>
</head>
<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>
<body>
<center>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <p class="text-right"> <a class="btn btn-primary" href="<?php echo $this->url(array("module"=>"admin","controller"=>"produtos","action"=>"addvenda"),null,true)?>">Adicionar Produto</a></p>
    <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
   <tr>
        <th><center>Descrição</center></th>        
        <th><center>Quantidade em Estoque</center></th>
        <th><center>Preço</center></th>
        <th><center>Código</center></th>
        <th><center>Data de Cadastro</center></th>
        <th><center>Ações</center></th>
   </tr>
   <?php foreach($this->paginator AS $key => $produto):?>
   <tr>
        <td><center><?php  echo $produto['descricao']?></center></td>
        <td><center><?php echo $produto['quantidade']?></center></td>
        <td><center><?php echo $produto['precoitem']?></center></td>
        <td><center><?php echo $produto['Codigo']?></center></td>
        <td><center><?php echo $produto['dtCriacao']?></center></td>
      <td><center>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"orcamento","action"=>"propostas","id"=>"{$produto['id']}"),null,true)?>" title="Editar"><span class="glyphicon glyphicon-pencil"></span> </a>
         <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"produtos","action"=>"deletepref","id"=>"{$produto['codigoRegistro']}","pref"=>"venda"),null,true)?>" onclick="javascript:return confirm('Você tem certeza que quer excluir este produto?')" title="Excluir"><span class="glyphicon glyphicon-remove"></span></a>
         </center>
      </td>
   </tr>
   <?php endforeach;?>
</table>
    
</center>
</body>