<script>
    var matriz=<?php echo json_encode($this->dadosPreferencias); ?>;
    var categorias = [];
    var segmentos = [];
    var produtos = [];
    var idTipo = 0;
    var idCategoria = 0;
    var Tipo = null;
    var Categoria = null;
    var Segmento = null;
    
    function teste(){
        var div = document.getElementById("formulario_produto");
        if(div){
            div.innerHTML = "";
        }
        
        var valor = $('#tipo').find(":selected").text();        
        if(valor != 'Selecione um tipo'){
            Tipo = valor;
            getCategoria();
        }if(valor == 'Selecione um tipo'){
            $('#teste').val('');
        }
    }
    
    function getCategoria(){
        categorias = [];  
        $("#categoria").empty();
        var option = document.createElement("option");
        option.text = "Selecione uma categoria";
        option.value = 0;
        var select = document.getElementById("categoria");
        select.appendChild(option);
        //var url = "/admin/categoria/pesquisarcategoria/id/"+idTipo;
        var url = "/admin/preferencias/listacategorias/filtro/venda/tipo/"+Tipo;
        var result = null;
        $.ajax({
        url: url,
        type: 'get',
        dataType: 'json',
        async: false,
            success: function(data) {
                result = data;
            }
        });
        if(result.length >0){
            for(var i=0;i<result.length;i++){
                var dados = new Array();
                dados["descricao"] = [result[i]['Categoria']];
                dados["id"] = [result[i]['idCategoria']];
                categorias.push(dados);
            }
            for(var i = 0; i<categorias.length;i++){
                //alert(categorias[i].toSource());
                var option = document.createElement("option");
                option.text = categorias[i]['descricao'];
                option.value = categorias[i]['id'];
                //option.value = "myvalue";
                var select = document.getElementById("categoria");
                select.appendChild(option);
            }

        }else{
            var option = document.createElement("option");
            option.text = "Tipo sem categorias cadastradas";
            option.value = 0;
            var select = document.getElementById("categoria");
            select.appendChild(option);
        }
    }
    
    function getSegmento(categoria){
        var valor = $(categoria).find(":selected").text(); 
        Categoria = valor;
        $("#segmento").empty();
        var option = document.createElement("option");
        option.text = "Selecione um segmento";
        option.value = 0;
        var select = document.getElementById("segmento");
        select.appendChild(option);

        segmentos = [];  
        //var url = "/admin/segmento/listasegmentos/id/"+idCategoria;
        var url = "/admin/preferencias/listasegmentos/filtro/venda/tipo/"+Tipo+"/categoria/"+Categoria;
        var result = null;
        $.ajax({
            url: url,
            type: 'get',
            dataType: 'json',
            async: false,
                success: function(data) {
                    result = data;
                }
        });
        if(result.length >0){
            for(var i=0;i<result.length;i++){
                var dados = new Array();
                dados["descricao"] = [result[i]['SubCategoria']];
                dados["id"] = [result[i]['idSubCategoria']];
                segmentos.push(dados);
            }
            for(var i = 0; i<segmentos.length;i++){
                var option = document.createElement("option");
                option.text = segmentos[i]['descricao'];
                option.value = segmentos[i]['id'];
                var select = document.getElementById("segmento");
                select.appendChild(option);
            }
        }else{
            $("#segmento").empty();
            var option = document.createElement("option");
            option.text = "Categoria sem segmentos cadastrados";
            option.value = 0;
            var select = document.getElementById("segmento");
            select.appendChild(option);
        }
    }
    
    function listarProdutos(segmento){
        var container = document.getElementById("produtos");
        var url = "/admin/produtos/listaprodutos/categoria/"+segmento;
        document.getElementById("produtos").innerHTML = "";
        var result = null;
        $.ajax({
            url: url,
            type: 'get',
            dataType: 'json',
            async: false,
                success: function(data) {
                    result = data;
                }
        });
        
        if(result.length >0){
            for(var i=0;i<result.length;i++){
                var dados = new Array();
                dados["descricao"] = [result[i]['descricao']];
                dados["id"] = [result[i]['id']];
                produtos.push(dados);
            }
            for(var i = 0; i<produtos.length;i++){
                var option = document.createElement("option");
                option.text = produtos[i]['descricao'];
                var checkbox = document.createElement('input');
                checkbox.type = "checkbox";
                checkbox.name = "produtos[]";
                checkbox.value = produtos[i]['id'];
                checkbox.id = produtos[i]['id'];
                var label = document.createElement('label')
                label.htmlFor = "id";
                label.appendChild(document.createTextNode(produtos[i]['descricao']));
                container.appendChild(checkbox);
                container.appendChild(label);
            }
            var enviar = document.createElement("input");
            enviar.type= "submit";
            enviar.value = "Adicionar produto";
            enviar.id = "add";
            enviar.name = "add";
            container.appendChild(enviar);
            var enviar = document.createElement("input");
            enviar.type= "submit";
            enviar.value = "Cadastrar novo produto";
            enviar.id = "enviar";
            enviar.name = "enviar";
            container.appendChild(enviar);
        }else{
            var enviar = document.createElement("input");
            enviar.type= "submit";
            enviar.value = "Cadastrar produto";
            enviar.id = "enviar";
            enviar.name = "enviar";
            container.appendChild(enviar);
        }
    }
    
</script>
<form method="post" name="form_categoria" id="form_categoria">
    <table>
        <tr>
            <th>Tipo</th>
            <th>Categoria</th>
            <th>Segmento</th>
        </tr>
        <tr>
            <td>
                <select name="tipo" id="tipo" onchange="teste()">
                    <option value="0">Selecione um tipo</option>
                    <?php    
                    foreach($this->dadosPreferencias as $key=>$value){
                        echo "<option value='".$value['idTipo']."'>".$value['Tipo']."</option>";
                    }
                    ?>
                </select>
            </td>
            <td>
                <select name="categoria" id="categoria" onchange="getSegmento(this)">
                    <option value="0">Selecione uma categoria</option>
                </select>
            </td>
            <td>
                <select name="segmento" id="segmento" onchange="listarProdutos(this.value)">
                    <option value="0">Selecione um segmento</option>
                </select>
            </td>
        </tr>
    </table>
    <br>
    <h3>Produtos cadastrados nesse segmento</h3>
    <br>
    <div id="produtos">
    </div>   
</form>
<hr>


<?php
    if($_POST):
        #die(var_dump($_POST));
        if(isset($_POST['add']) && isset($_POST['produtos'])):
            //die(var_dump($_POST));
        ?>
        <!-- count($_POST["produtos"])>0 -->
            <script>
                function getFormData($form){
                    var unindexed_array = $form.serializeArray();
                    var indexed_array = {};
                    $.map(unindexed_array, function(n, i){
                        indexed_array[n['name']] = n['value'];
                    });
                    return indexed_array;
                }
                var data = <?php echo json_encode($_POST)?>;
                 $.ajax({
                    type: 'post',
                    url: '/admin/produtos/addprodutovenda/',
                    data: data,
                    dataType: 'json',
                });
            </script>
        <?php endif;
        if(isset($_POST['enviar'])):?>
            <div name="formulario_produto" id = "formulario_produto" class="col-md-offset-3 col-md-4">
                <form name="form_produto" method="get" action="<?php echo $this->url(array("module"=>"admin","controller"=>"produtos","action"=>"addprodutovenda"),null,true);?>">
                    <input type="text" name="nome_produto" id="nome_produto" class="form-control" placeholder="Nome do produto">
                    <input type="text" name="quantidade_produto" id="quantidade_produto" class="form-control" placeholder="Quantidade Disponível">
                    <input type="text" name="preco_produto" id="preco_produto" class="form-control" placeholder="Preço do Produto">
                    <input type="text" name="codigo_produto" id="codigo_produto" class="form-control" placeholder="Referência do produto">
                    <input type="hidden" name="produto_tipo" id="produto_tipo" class="form-control" value="<?php echo $_POST['tipo']?>">
                    <input type="hidden" name="produto_categoria" id="produto_categoria" class="form-control" value="<?php echo $_POST['categoria']?>">
                    <input type="hidden" name="produto_segmento" id="produto_segmento" class="form-control" value="<?php echo $_POST['segmento']?>">
                    <hr>
                    <input type="submit" name="submit" class="btn btn btn-lg btn-primary btn-block" value="Cadastrar Produto">
                </form>
            </div>
        <?php
            endif;
        ?>
    <?php endif;
?>