<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>
<body>
<center>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    <p class="text-right"> <a class="btn btn-primary" href="<?php echo $this->url(array("module"=>"admin","controller"=>"noticias","action"=>"new"),null,true)?>">Adicionar</a></p>
    <table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
   <tr>
        <th><center>Id</center></th>
        <th><center>Título</center></th>    
        <th><center>Descrição</center></th>        
        <th><center>Patrocinador</center></th>        
   </tr>
   <?php foreach($this->paginator AS $key => $categoria): ?>
   <tr>
        <td><center><?php  echo $categoria['idnoticia']?></center></td>
        <td><center><?php  echo $categoria['titulo']?></center></td>
        <td><center><?php  echo $categoria['descricao']?></center></td>
        <td><center><?php  echo $categoria['nome']?></center></td>
   </tr>
   <?php endforeach;?>
</table>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
    
</center>
</body>