<?php
$produto = $this->dados;
?>
<style>
    table{
        width: 100%
    }
</style>
<h2>Visualização de cadastro de produto</h2>
<br>

<div class="row">
    <div class="col-md-6 col-md-offset-2">
        <div class="table-responsive">
            <table class="table-bordered table-condensed table-striped table-hover">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Status</th>
                    <th>Data de cadastro</th>
                </tr>
                <?php
                    echo "<tr>";
                        echo "<td>".$produto['id']."</td>";
                        echo "<td>".$produto['descricao']."</td>";
                        echo "<td>".Admin_Model_Status::pesquisaStatus($produto['status'])."</td>";
                        echo "<td>".$produto['dtCriacao']."</td>";
                    echo "</tr>";
                ?>
            </table>
            <a href="<?php echo $this->url(array("module"=>"admin","controller"=>"revisao","action"=>"index"),null,true);?>" title="Voltar"><span class="icon icon-arrow-left"></span></a>
        </div>
    </div>
</div>